// Curated Singapore food seed — REAL values, hand-sourced + HPB-anchored.
// AUTO-RECONCILED from data/foods.json (the live DB) so this stays the source of truth.
//
// HONESTY RULE: a nutrient is `N` (null) when a reliable per-serving value is not known
// (never 0). Macros/sodium for hawker dishes are HPB-consistent (Energy & Nutrient
// Composition / iDAT, cross-checked to sum to the stated kcal). Micros use standard
// composition values or null. Numbers are rounded, per serving. Nutrition guidance, not lab data.
//
// Fields: kcal, protein_g, carbs_g, sugar_g, fat_g, fiber_g, sodium_mg, vitamin_c_mg,
// vitamin_d_iu, calcium_mg, magnesium_mg, zinc_mg, iron_mg, potassium_mg, omega3_mg,
// glycine_g, choline_mg. Optional: place (named SG chain/stall).

const N = null;
const defaults = {
  kcal: N,
  protein_g: N,
  carbs_g: N,
  sugar_g: N,
  fat_g: N,
  fiber_g: N,
  sodium_mg: N,
  vitamin_c_mg: N,
  vitamin_d_iu: N,
  calcium_mg: N,
  magnesium_mg: N,
  zinc_mg: N,
  iron_mg: N,
  potassium_mg: N,
  omega3_mg: N,
  glycine_g: N,
  choline_mg: N,
};
function f(name, serving, tags, v, place) {
  const o = { name, serving, sg_local: true, source: 'seed', tags: tags || [], ...defaults, ...v };
  if (place) o.place = place;
  return o;
}

const SEED = [
  f("Hainanese Chicken Rice", "1 plate (~450g)", ["high-glycemic"], { kcal: 607, protein_g: 23, carbs_g: 75, sugar_g: 2, fat_g: 23, fiber_g: 1, sodium_mg: 1220, glycine_g: 1.2 }),
  f("Char Kway Teow", "1 plate (~350g)", ["high-glycemic", "high-fat"], { kcal: 744, protein_g: 23, carbs_g: 76, sugar_g: 6, fat_g: 38, fiber_g: 3, sodium_mg: 1460 }),
  f("Laksa", "1 bowl (~500g)", ["high-fat", "high-sodium"], { kcal: 590, protein_g: 22, carbs_g: 55, sugar_g: 6, fat_g: 32, fiber_g: 3, sodium_mg: 2200 }),
  f("Nasi Lemak (with fried chicken)", "1 plate", ["high-glycemic", "high-fat"], { kcal: 790, protein_g: 28, carbs_g: 80, sugar_g: 5, fat_g: 40, fiber_g: 3, sodium_mg: 1300 }),
  f("Bak Chor Mee (dry)", "1 bowl", ["high-glycemic"], { kcal: 511, protein_g: 22, carbs_g: 68, sugar_g: 4, fat_g: 16, fiber_g: 3, sodium_mg: 1590 }),
  f("Fishball Noodle Soup", "1 bowl", [], { kcal: 340, protein_g: 20, carbs_g: 52, sugar_g: 3, fat_g: 6, fiber_g: 2, sodium_mg: 1420 }),
  f("Wanton Mee (dry)", "1 bowl", ["high-glycemic"], { kcal: 409, protein_g: 19, carbs_g: 59, sugar_g: 5, fat_g: 11, fiber_g: 3, sodium_mg: 1330 }),
  f("Roti Prata (2 plain + curry)", "2 pieces + curry", ["high-glycemic", "high-fat"], { kcal: 560, protein_g: 12, carbs_g: 66, sugar_g: 4, fat_g: 27, fiber_g: 3, sodium_mg: 900 }),
  f("Economic Rice (3 veg + 1 meat)", "1 plate", [], { kcal: 620, protein_g: 25, carbs_g: 78, sugar_g: 6, fat_g: 22, fiber_g: 5, sodium_mg: 1200, vitamin_c_mg: 15 }),
  f("Yong Tau Foo (soup, 6 pcs + noodle)", "1 bowl", ["balanced"], { kcal: 380, protein_g: 24, carbs_g: 45, sugar_g: 5, fat_g: 11, fiber_g: 5, sodium_mg: 1500, calcium_mg: 120 }),
  f("Chicken Breast (steamed, no skin)", "150g", ["high-protein", "lean"], { kcal: 248, protein_g: 47, carbs_g: 0, sugar_g: 0, fat_g: 5, fiber_g: 0, sodium_mg: 105, calcium_mg: 8, magnesium_mg: 44, zinc_mg: 1.5, iron_mg: 0.7, potassium_mg: 384, glycine_g: 2.1, choline_mg: 130 }),
  f("Fish Soup (sliced, with rice)", "1 bowl", ["high-protein", "lean"], { kcal: 420, protein_g: 33, carbs_g: 45, sugar_g: 3, fat_g: 11, fiber_g: 2, sodium_mg: 1600, vitamin_d_iu: 120, omega3_mg: 400 }),
  f("Thunder Tea Rice (Lei Cha)", "1 bowl", ["high-fiber", "balanced"], { kcal: 450, protein_g: 18, carbs_g: 65, sugar_g: 6, fat_g: 12, fiber_g: 10, sodium_mg: 900, vitamin_c_mg: 30, magnesium_mg: 90 }),
  f("Popiah", "1 roll", ["high-fiber"], { kcal: 240, protein_g: 8, carbs_g: 34, sugar_g: 8, fat_g: 8, fiber_g: 5, sodium_mg: 650, vitamin_c_mg: 18 }),
  f("Soya Bean Milk (unsweetened)", "1 cup (250ml)", [], { kcal: 80, protein_g: 7, carbs_g: 4, sugar_g: 1, fat_g: 4, fiber_g: 1, sodium_mg: 30, calcium_mg: 60, magnesium_mg: 40 }),
  f("Kaya Toast set (2 toast, no drink)", "2 slices", ["high-glycemic", "high-sugar"], { kcal: 380, protein_g: 8, carbs_g: 42, sugar_g: 18, fat_g: 20, fiber_g: 1, sodium_mg: 480 }),
  f("Teh Tarik (with condensed milk)", "1 cup", ["high-sugar"], { kcal: 170, protein_g: 3, carbs_g: 28, sugar_g: 26, fat_g: 5, fiber_g: 0, sodium_mg: 55, calcium_mg: 90 }),
  f("Kopi (with condensed milk)", "1 cup", ["high-sugar"], { kcal: 115, protein_g: 2, carbs_g: 20, sugar_g: 19, fat_g: 3, fiber_g: 0, sodium_mg: 40 }),
  f("Kiwi fruit", "1 fruit (~75g)", ["vitamin-c", "anti-inflammatory"], { kcal: 42, protein_g: 0.8, carbs_g: 10, sugar_g: 6, fiber_g: 2, vitamin_c_mg: 64, calcium_mg: 26, magnesium_mg: 12, zinc_mg: 0.1, iron_mg: 0.2, potassium_mg: 215 }),
  f("Orange", "1 medium (~130g)", ["vitamin-c"], { kcal: 62, protein_g: 1.2, carbs_g: 15, sugar_g: 12, fiber_g: 3, vitamin_c_mg: 70, calcium_mg: 52, magnesium_mg: 13, zinc_mg: 0.1, iron_mg: 0.1, potassium_mg: 237 }),
  f("Red bell pepper", "1 cup raw (~150g)", ["vitamin-c", "collagen-synthesis"], { kcal: 39, protein_g: 1.5, carbs_g: 9, sugar_g: 6, fiber_g: 3, vitamin_c_mg: 190, calcium_mg: 11, magnesium_mg: 18, zinc_mg: 0.4, iron_mg: 0.6, potassium_mg: 314 }),
  f("Guava", "1 fruit (~55g)", ["vitamin-c"], { kcal: 37, protein_g: 1.4, carbs_g: 8, sugar_g: 5, fiber_g: 3, vitamin_c_mg: 125, calcium_mg: 10, magnesium_mg: 12, zinc_mg: 0.1, iron_mg: 0.1, potassium_mg: 229 }),
  f("Salmon (cooked)", "150g fillet", ["omega-3", "high-protein", "anti-inflammatory"], { kcal: 280, protein_g: 40, fat_g: 13, sodium_mg: 90, vitamin_d_iu: 800, calcium_mg: 23, magnesium_mg: 45, zinc_mg: 0.6, iron_mg: 0.5, potassium_mg: 700, omega3_mg: 3500, choline_mg: 140 }),
  f("Sardines (canned in water)", "1 tin (~90g)", ["omega-3", "calcium", "high-protein"], { kcal: 180, protein_g: 22, fat_g: 10, sodium_mg: 400, vitamin_d_iu: 180, calcium_mg: 350, magnesium_mg: 35, zinc_mg: 1.2, iron_mg: 2.5, potassium_mg: 357, omega3_mg: 1400 }),
  f("Eggs (2, whole, cooked)", "2 large", ["high-protein", "choline"], { kcal: 156, protein_g: 13, fat_g: 11, sodium_mg: 140, vitamin_d_iu: 90, calcium_mg: 56, magnesium_mg: 12, zinc_mg: 1.3, iron_mg: 1.8, potassium_mg: 138, glycine_g: 0.5, choline_mg: 294 }),
  f("Greek yogurt (plain, nonfat)", "1 cup (~170g)", ["high-protein", "calcium", "probiotic"], { kcal: 100, protein_g: 17, carbs_g: 6, sugar_g: 6, fat_g: 0, sodium_mg: 60, calcium_mg: 190, magnesium_mg: 20, zinc_mg: 1, iron_mg: 0.1, potassium_mg: 240 }),
  f("Spinach (cooked)", "1 cup (~180g)", ["magnesium", "iron", "nitrate"], { kcal: 41, protein_g: 5, carbs_g: 7, fiber_g: 4, sodium_mg: 125, vitamin_c_mg: 18, calcium_mg: 245, magnesium_mg: 157, iron_mg: 6, potassium_mg: 839 }),
  f("Pumpkin seeds", "1 oz (~28g)", ["magnesium", "zinc"], { kcal: 151, protein_g: 7, carbs_g: 5, fat_g: 13, fiber_g: 2, calcium_mg: 13, magnesium_mg: 150, zinc_mg: 2.2, iron_mg: 2.3, potassium_mg: 226 }),
  f("Oysters (cooked)", "6 medium (~85g)", ["zinc", "high-protein"], { kcal: 68, protein_g: 8, fat_g: 2, sodium_mg: 175, vitamin_d_iu: 270, calcium_mg: 38, magnesium_mg: 40, zinc_mg: 32, iron_mg: 6, potassium_mg: 143, omega3_mg: 600 }),
  f("Lean beef (cooked)", "150g", ["high-protein", "zinc", "iron", "creatine"], { kcal: 320, protein_g: 47, fat_g: 14, sodium_mg: 90, calcium_mg: 27, magnesium_mg: 36, zinc_mg: 9, iron_mg: 4, potassium_mg: 495, glycine_g: 2.4, choline_mg: 140 }),
  f("Bone broth", "1 cup (250ml)", ["glycine", "collagen-synthesis", "gut"], { kcal: 50, protein_g: 9, sodium_mg: 500, calcium_mg: 15, magnesium_mg: 6, glycine_g: 2.5 }),
  f("Gelatin / collagen peptides", "1 scoop (~11g)", ["glycine", "collagen-synthesis"], { kcal: 40, protein_g: 10, sodium_mg: 30, glycine_g: 2.2 }),
  f("Whey protein isolate", "1 scoop (~30g)", ["high-protein", "leucine"], { kcal: 120, protein_g: 25, carbs_g: 2, sugar_g: 1, fat_g: 1, sodium_mg: 60, calcium_mg: 130, glycine_g: 0.4 }),
  f("Tofu (firm)", "150g", ["high-protein", "calcium", "magnesium"], { kcal: 220, protein_g: 24, carbs_g: 5, fat_g: 13, sodium_mg: 20, calcium_mg: 525, magnesium_mg: 88, zinc_mg: 2.4, iron_mg: 4, potassium_mg: 182 }),
  f("Blueberries", "1 cup (~148g)", ["polyphenol", "anti-inflammatory"], { kcal: 84, protein_g: 1, carbs_g: 21, sugar_g: 15, fiber_g: 4, vitamin_c_mg: 14, calcium_mg: 9, magnesium_mg: 9, zinc_mg: 0.2, iron_mg: 0.4, potassium_mg: 114 }),
  f("Broccoli (cooked)", "1 cup (~156g)", ["vitamin-c", "fiber", "sulforaphane"], { kcal: 55, protein_g: 4, carbs_g: 11, fiber_g: 5, sodium_mg: 64, vitamin_c_mg: 101, calcium_mg: 62, magnesium_mg: 33, potassium_mg: 457 }),
  f("Almonds", "1 oz (~28g)", ["magnesium", "healthy-fat", "vitamin-e"], { kcal: 164, protein_g: 6, carbs_g: 6, fat_g: 14, fiber_g: 4, calcium_mg: 76, magnesium_mg: 76, zinc_mg: 0.9, iron_mg: 1, potassium_mg: 208 }),
  f("Oats (rolled, dry)", "1/2 cup (~40g)", ["fiber", "beta-glucan", "low-glycemic"], { kcal: 150, protein_g: 5, carbs_g: 27, sugar_g: 1, fiber_g: 4, magnesium_mg: 55, zinc_mg: 1.5, iron_mg: 1.7 }),
  f("Sweet potato (baked)", "1 medium (~150g)", ["low-glycemic", "vitamin-a", "fiber"], { kcal: 130, protein_g: 3, carbs_g: 30, sugar_g: 9, fiber_g: 5, vitamin_c_mg: 20, calcium_mg: 57, magnesium_mg: 33, zinc_mg: 0.5, iron_mg: 1, potassium_mg: 540 }),
  f("Avocado", "1/2 fruit (~100g)", ["healthy-fat", "potassium", "fiber"], { kcal: 160, protein_g: 2, carbs_g: 9, fat_g: 15, fiber_g: 7, vitamin_c_mg: 10, calcium_mg: 12, magnesium_mg: 29, zinc_mg: 0.6, iron_mg: 0.6, potassium_mg: 485 }),
  f("Dark leafy salad (mixed)", "2 cups", ["fiber", "nitrate", "folate"], { kcal: 20, protein_g: 2, carbs_g: 4, fiber_g: 2, sodium_mg: 30, vitamin_c_mg: 25, magnesium_mg: 25, potassium_mg: 300 }),
  f("Cottage cheese (low-fat)", "1 cup (~225g)", ["high-protein", "casein", "calcium"], { kcal: 180, protein_g: 25, carbs_g: 8, sugar_g: 7, fat_g: 5, sodium_mg: 700, calcium_mg: 138, magnesium_mg: 25, zinc_mg: 0.9, iron_mg: 0.3, potassium_mg: 308 }),
  f("Tuna (canned in water)", "1 tin (~100g)", ["high-protein", "lean", "omega-3"], { kcal: 116, protein_g: 26, fat_g: 1, sodium_mg: 320, vitamin_d_iu: 60, calcium_mg: 11, magnesium_mg: 25, zinc_mg: 0.6, iron_mg: 1, potassium_mg: 237, omega3_mg: 300 }),
  f("Dark chocolate (85%)", "2 squares (~20g)", ["magnesium", "polyphenol"], { kcal: 120, protein_g: 2, carbs_g: 8, sugar_g: 4, fat_g: 9, fiber_g: 2, calcium_mg: 15, magnesium_mg: 45, zinc_mg: 0.7, iron_mg: 2, potassium_mg: 143 }),
  f("Hokkien Mee (fried prawn)", "1 plate (~350g)", ["high-sodium"], { kcal: 560, protein_g: 24, carbs_g: 62, sugar_g: 3, fat_g: 24, fiber_g: 3, sodium_mg: 1400 }),
  f("Mee Goreng (mamak)", "1 plate", ["high-glycemic", "high-sodium"], { kcal: 660, protein_g: 18, carbs_g: 90, sugar_g: 12, fat_g: 24, fiber_g: 4, sodium_mg: 1500 }),
  f("Mee Rebus", "1 bowl", ["high-sodium"], { kcal: 490, protein_g: 16, carbs_g: 78, sugar_g: 10, fat_g: 12, fiber_g: 5, sodium_mg: 1300 }),
  f("Mee Siam", "1 plate", ["high-glycemic"], { kcal: 470, protein_g: 12, carbs_g: 75, sugar_g: 12, fat_g: 14, fiber_g: 4, sodium_mg: 1250 }),
  f("Prawn Mee Soup (Hae Mee)", "1 bowl", ["high-sodium"], { kcal: 480, protein_g: 22, carbs_g: 60, sugar_g: 3, fat_g: 16, fiber_g: 3, sodium_mg: 1600 }),
  f("Lor Mee", "1 bowl", ["high-sodium"], { kcal: 520, protein_g: 20, carbs_g: 72, sugar_g: 6, fat_g: 16, fiber_g: 3, sodium_mg: 1500 }),
  f("Ban Mian (soup)", "1 bowl", ["high-sodium"], { kcal: 470, protein_g: 20, carbs_g: 58, sugar_g: 3, fat_g: 16, fiber_g: 3, sodium_mg: 1400 }),
  f("Bak Kut Teh (with rice)", "1 set", ["high-sodium", "high-protein"], { kcal: 560, protein_g: 34, carbs_g: 50, sugar_g: 2, fat_g: 24, fiber_g: 1, sodium_mg: 1900 }),
  f("Nasi Briyani (chicken)", "1 plate", ["high-glycemic"], { kcal: 880, protein_g: 34, carbs_g: 95, sugar_g: 6, fat_g: 40, fiber_g: 4, sodium_mg: 1600 }),
  f("Char Siew Rice", "1 plate", ["high-glycemic"], { kcal: 620, protein_g: 28, carbs_g: 82, sugar_g: 12, fat_g: 20, fiber_g: 2, sodium_mg: 1300 }),
  f("Roasted Duck Rice", "1 plate", ["high-sodium"], { kcal: 680, protein_g: 30, carbs_g: 80, sugar_g: 6, fat_g: 28, fiber_g: 2, sodium_mg: 1400 }),
  f("Fish Head Curry (with rice)", "1 serving", ["high-sodium"], { kcal: 650, protein_g: 35, carbs_g: 60, sugar_g: 8, fat_g: 30, fiber_g: 4, sodium_mg: 1700 }),
  f("Beef Hor Fun", "1 plate", ["high-sodium"], { kcal: 620, protein_g: 26, carbs_g: 70, sugar_g: 6, fat_g: 26, fiber_g: 3, sodium_mg: 1500 }),
  f("Fried Carrot Cake (black)", "1 plate", ["high-sodium"], { kcal: 560, protein_g: 12, carbs_g: 62, sugar_g: 12, fat_g: 30, fiber_g: 3, sodium_mg: 1400 }),
  f("Oyster Omelette (Orh Luak)", "1 plate", ["high-sodium"], { kcal: 480, protein_g: 18, carbs_g: 30, sugar_g: 3, fat_g: 32, fiber_g: 1, sodium_mg: 1100, zinc_mg: 8 }),
  f("Chicken Satay (10 sticks + sauce)", "10 sticks", ["high-protein"], { kcal: 520, protein_g: 34, carbs_g: 22, sugar_g: 14, fat_g: 32, fiber_g: 3, sodium_mg: 900 }),
  f("Rojak (fruit & vegetable)", "1 plate", [], { kcal: 380, protein_g: 8, carbs_g: 55, sugar_g: 30, fat_g: 14, fiber_g: 8, sodium_mg: 900, vitamin_c_mg: 40 }),
  f("Chwee Kueh (4 pcs)", "4 pieces", [], { kcal: 300, protein_g: 5, carbs_g: 48, sugar_g: 6, fat_g: 10, fiber_g: 2, sodium_mg: 800 }),
  f("Chai Tow Kway (white)", "1 plate", ["high-sodium"], { kcal: 480, protein_g: 10, carbs_g: 58, sugar_g: 6, fat_g: 24, fiber_g: 2, sodium_mg: 1200 }),
  f("Curry Puff (1)", "1 piece", [], { kcal: 260, protein_g: 6, carbs_g: 28, sugar_g: 3, fat_g: 14, fiber_g: 2, sodium_mg: 350 }),
  f("Roti John", "1 whole", ["high-sodium"], { kcal: 620, protein_g: 26, carbs_g: 60, sugar_g: 6, fat_g: 32, fiber_g: 3, sodium_mg: 1200 }),
  f("Murtabak (chicken, half)", "1/2 piece", ["high-sodium"], { kcal: 600, protein_g: 28, carbs_g: 62, sugar_g: 6, fat_g: 28, fiber_g: 3, sodium_mg: 1200 }),
  f("Char Siew Bao (1)", "1 bun", [], { kcal: 240, protein_g: 8, carbs_g: 38, sugar_g: 10, fat_g: 6, fiber_g: 1, sodium_mg: 400 }),
  f("You Tiao (dough fritter)", "1 piece", [], { kcal: 250, protein_g: 5, carbs_g: 30, sugar_g: 1, fat_g: 12, fiber_g: 1, sodium_mg: 400 }),
  f("Chicken Porridge", "1 bowl", [], { kcal: 280, protein_g: 16, carbs_g: 44, sugar_g: 1, fat_g: 5, fiber_g: 1, sodium_mg: 900 }),
  f("Fish Porridge", "1 bowl", ["high-protein"], { kcal: 300, protein_g: 22, carbs_g: 42, sugar_g: 1, fat_g: 6, fiber_g: 1, sodium_mg: 950 }),
  f("Wholemeal Bread (2 slices)", "2 slices", ["high-fiber"], { kcal: 160, protein_g: 8, carbs_g: 28, sugar_g: 3, fat_g: 2, fiber_g: 4, sodium_mg: 300 }),
  f("White Rice (cooked)", "1 bowl (~200g)", ["high-glycemic"], { kcal: 260, protein_g: 5, carbs_g: 57, sugar_g: 0, fat_g: 0.5, fiber_g: 1, sodium_mg: 2 }),
  f("Brown Rice (cooked)", "1 bowl (~200g)", ["high-fiber"], { kcal: 240, protein_g: 5, carbs_g: 50, sugar_g: 0, fat_g: 2, fiber_g: 4, sodium_mg: 5, magnesium_mg: 84 }),
  f("Durian (flesh)", "3 seeds (~100g)", ["high-glycemic"], { kcal: 147, protein_g: 1.5, carbs_g: 27, sugar_g: 20, fat_g: 5, fiber_g: 4, vitamin_c_mg: 20, potassium_mg: 436 }),
  f("Papaya", "1 cup (~140g)", [], { kcal: 60, protein_g: 0.7, carbs_g: 15, sugar_g: 11, fat_g: 0.4, fiber_g: 2.5, vitamin_c_mg: 88, potassium_mg: 264 }),
  f("Dragonfruit", "1 cup", ["high-fiber"], { kcal: 60, protein_g: 1.2, carbs_g: 13, sugar_g: 8, fat_g: 0, fiber_g: 3, vitamin_c_mg: 4, magnesium_mg: 40 }),
  f("Rambutan", "5 pieces", [], { kcal: 60, protein_g: 0.7, carbs_g: 15, sugar_g: 13, fat_g: 0.2, fiber_g: 1, vitamin_c_mg: 20 }),
  f("Soursop", "1 cup", [], { kcal: 66, protein_g: 1, carbs_g: 17, sugar_g: 14, fat_g: 0.3, fiber_g: 3, vitamin_c_mg: 20 }),
  f("Bubble Milk Tea (with pearls)", "500ml", ["high-glycemic"], { kcal: 340, protein_g: 3, carbs_g: 70, sugar_g: 55, fat_g: 6, fiber_g: 0, sodium_mg: 80 }),
  f("Milo Dinosaur", "1 cup", ["high-glycemic"], { kcal: 340, protein_g: 8, carbs_g: 56, sugar_g: 48, fat_g: 9, fiber_g: 2, calcium_mg: 200 }),
  f("Bandung (rose milk)", "1 cup", ["high-glycemic"], { kcal: 200, protein_g: 4, carbs_g: 38, sugar_g: 36, fat_g: 4, fiber_g: 0 }),
  f("Sugarcane Juice", "1 cup", ["high-glycemic"], { kcal: 180, protein_g: 0, carbs_g: 45, sugar_g: 43, fat_g: 0, fiber_g: 0 }),
  f("Kopi O (black, no sugar)", "1 cup", [], { kcal: 5, protein_g: 0, carbs_g: 1, sugar_g: 0, fat_g: 0, fiber_g: 0, sodium_mg: 5, potassium_mg: 90 }),
  f("Teh O (no milk, no sugar)", "1 cup", [], { kcal: 2, protein_g: 0, carbs_g: 0.5, sugar_g: 0, fat_g: 0, fiber_g: 0 }),
  f("Barley Water (sweetened)", "1 cup", ["high-glycemic"], { kcal: 90, protein_g: 1, carbs_g: 22, sugar_g: 20, fat_g: 0, fiber_g: 1 }),
  f("Ondeh Ondeh (5 pcs)", "5 pieces", [], { kcal: 200, protein_g: 2, carbs_g: 34, sugar_g: 18, fat_g: 7, fiber_g: 2 }),
  f("Ang Ku Kueh (1)", "1 piece", [], { kcal: 150, protein_g: 3, carbs_g: 30, sugar_g: 10, fat_g: 2, fiber_g: 1 }),
  f("Kaya (coconut jam)", "2 tbsp", [], { kcal: 90, protein_g: 1, carbs_g: 12, sugar_g: 11, fat_g: 4, fiber_g: 0 }),
  f("Claypot Rice", "1 claypot (~450g)", ["high-glycemic", "high-fat"], { kcal: 896, protein_g: 32, carbs_g: 100, sugar_g: 4, fat_g: 38, fiber_g: 3, sodium_mg: 1500 }),
  f("Murtabak (Mutton, whole)", "1 whole", ["high-fat", "high-glycemic"], { kcal: 1102, protein_g: 45, carbs_g: 90, sugar_g: 8, fat_g: 60, fiber_g: 4, sodium_mg: 1400 }),
  f("Ngoh Hiang (mixed platter)", "1 platter", ["high-fat"], { kcal: 805, protein_g: 30, carbs_g: 55, sugar_g: 8, fat_g: 50, fiber_g: 3, sodium_mg: 1300 }),
  f("Lontong (with Sayur Lodeh)", "1 bowl", ["high-fat"], { kcal: 798, protein_g: 22, carbs_g: 85, sugar_g: 8, fat_g: 40, fiber_g: 6, sodium_mg: 1400 }),
  f("Kway Chap", "1 bowl + rice", ["high-sodium"], { kcal: 650, protein_g: 30, carbs_g: 55, sugar_g: 4, fat_g: 33, fiber_g: 2, sodium_mg: 1600 }),
  f("Mui Fan (seafood rice)", "1 plate", ["high-glycemic"], { kcal: 719, protein_g: 28, carbs_g: 90, sugar_g: 5, fat_g: 26, fiber_g: 3, sodium_mg: 1500 }),
  f("Fried Rice (Chinese)", "1 plate", ["high-glycemic"], { kcal: 576, protein_g: 16, carbs_g: 78, sugar_g: 4, fat_g: 22, fiber_g: 2, sodium_mg: 1200 }),
  f("Fried Bee Hoon (with items)", "1 plate", ["high-glycemic"], { kcal: 369, protein_g: 15, carbs_g: 50, sugar_g: 4, fat_g: 11, fiber_g: 2, sodium_mg: 1100 }),
  f("Curry Chicken Noodle", "1 bowl", ["high-fat", "high-sodium"], { kcal: 695, protein_g: 26, carbs_g: 68, sugar_g: 8, fat_g: 34, fiber_g: 4, sodium_mg: 1600 }),
  f("Ipoh Hor Fun", "1 bowl", [], { kcal: 452, protein_g: 24, carbs_g: 60, sugar_g: 4, fat_g: 12, fiber_g: 2, sodium_mg: 1500 }),
  f("Mee Soto", "1 bowl", ["high-sodium"], { kcal: 433, protein_g: 22, carbs_g: 50, sugar_g: 5, fat_g: 15, fiber_g: 3, sodium_mg: 1600 }),
  f("Soya Sauce Chicken Rice", "1 plate", ["high-glycemic"], { kcal: 551, protein_g: 26, carbs_g: 78, sugar_g: 5, fat_g: 15, fiber_g: 1, sodium_mg: 1300 }),
  f("Braised Duck Rice", "1 plate", ["high-glycemic"], { kcal: 604, protein_g: 28, carbs_g: 80, sugar_g: 4, fat_g: 20, fiber_g: 1, sodium_mg: 1400 }),
  f("Fried Ee Mee (seafood)", "1 plate", ["high-fat", "high-glycemic"], { kcal: 1010, protein_g: 30, carbs_g: 100, sugar_g: 6, fat_g: 55, fiber_g: 3, sodium_mg: 1900 }),
  f("Fried Hong Kong Noodles", "1 plate", ["high-fat", "high-glycemic"], { kcal: 693, protein_g: 24, carbs_g: 78, sugar_g: 6, fat_g: 32, fiber_g: 3, sodium_mg: 1600 }),
  f("Beef Ball Kway Teow Soup", "1 bowl", [], { kcal: 656, protein_g: 30, carbs_g: 75, sugar_g: 4, fat_g: 24, fiber_g: 3, sodium_mg: 1700 }),
  f("Fried Fish Bee Hoon Soup (with milk)", "1 bowl", ["high-fat"], { kcal: 730, protein_g: 30, carbs_g: 55, sugar_g: 4, fat_g: 42, fiber_g: 2, sodium_mg: 1500 }),
  f("Sliced Fish Bee Hoon Soup (clear)", "1 bowl", ["balanced"], { kcal: 349, protein_g: 25, carbs_g: 45, sugar_g: 3, fat_g: 8, fiber_g: 2, sodium_mg: 1300 }),
  f("Nasi Goreng", "1 plate", ["high-glycemic", "high-fat"], { kcal: 920, protein_g: 26, carbs_g: 100, sugar_g: 8, fat_g: 45, fiber_g: 5, sodium_mg: 1700 }),
  f("Chicken Teriyaki Don", "1 bowl", ["high-glycemic"], { kcal: 641, protein_g: 30, carbs_g: 85, sugar_g: 12, fat_g: 18, fiber_g: 2, sodium_mg: 1400 }),
  f("Tom Yam Seafood Soup", "1 bowl", ["high-sodium"], { kcal: 271, protein_g: 22, carbs_g: 18, sugar_g: 6, fat_g: 12, fiber_g: 2, sodium_mg: 1600 }),
  f("Macaroni Chicken Soup", "1 bowl", ["balanced"], { kcal: 277, protein_g: 18, carbs_g: 40, sugar_g: 4, fat_g: 5, fiber_g: 2, sodium_mg: 1200 }),
  f("Pork Porridge (Teochew)", "1 bowl", [], { kcal: 293, protein_g: 18, carbs_g: 45, sugar_g: 2, fat_g: 5, fiber_g: 1, sodium_mg: 1100 }),
  f("Nasi Lemak (plain)", "1 packet", ["high-glycemic"], { kcal: 279, protein_g: 7, carbs_g: 40, sugar_g: 3, fat_g: 11, fiber_g: 2, sodium_mg: 700 }),
  f("Curry Chicken (with gravy)", "1 serving", ["high-fat"], { kcal: 450, protein_g: 30, carbs_g: 12, sugar_g: 5, fat_g: 32, fiber_g: 2, sodium_mg: 1300 }),
  f("Pork Satay (10 sticks + sauce)", "10 sticks", ["high-fat", "high-protein"], { kcal: 427, protein_g: 30, carbs_g: 15, sugar_g: 8, fat_g: 26, fiber_g: 2, sodium_mg: 900 }),
  f("Char Siew & Sio Bak Rice", "1 plate", ["high-glycemic", "high-fat"], { kcal: 600, protein_g: 26, carbs_g: 78, sugar_g: 4, fat_g: 22, fiber_g: 1, sodium_mg: 1300 }),
  f("Cereal Prawns", "1 plate", ["high-fat"], { kcal: 450, protein_g: 28, carbs_g: 25, sugar_g: 6, fat_g: 26, fiber_g: 1, sodium_mg: 800 }, "Zi char"),
  f("Sweet & Sour Pork", "1 plate", ["high-fat"], { kcal: 500, protein_g: 24, carbs_g: 45, sugar_g: 20, fat_g: 26, fiber_g: 2, sodium_mg: 900 }, "Zi char"),
  f("Sambal Kang Kong", "1 plate", ["high-fat"], { kcal: 185, protein_g: 5, carbs_g: 12, sugar_g: 4, fat_g: 13, fiber_g: 4, sodium_mg: 800 }, "Zi char"),
  f("Salted Egg Chicken", "1 plate", ["high-fat"], { kcal: 520, protein_g: 28, carbs_g: 30, sugar_g: 6, fat_g: 32, fiber_g: 1, sodium_mg: 900 }, "Zi char"),
  f("Hotplate Tofu", "1 plate", ["high-fat"], { kcal: 330, protein_g: 16, carbs_g: 20, sugar_g: 6, fat_g: 22, fiber_g: 3, sodium_mg: 900 }, "Zi char"),
  f("Prawn Paste Chicken (Har Cheong Gai)", "4 pieces", ["high-fat", "high-protein"], { kcal: 340, protein_g: 26, carbs_g: 10, sugar_g: 2, fat_g: 22, fiber_g: 0, sodium_mg: 800 }, "Zi char"),
  f("Sambal Stingray (BBQ)", "1 portion", ["high-protein"], { kcal: 300, protein_g: 30, carbs_g: 6, sugar_g: 4, fat_g: 18, fiber_g: 2, sodium_mg: 900 }),
  f("Siew Mai (3 pcs)", "3 pieces", [], { kcal: 315, protein_g: 15, carbs_g: 20, sugar_g: 2, fat_g: 18, fiber_g: 1, sodium_mg: 700 }),
  f("Har Gow (4 pcs)", "4 pieces", [], { kcal: 200, protein_g: 10, carbs_g: 24, sugar_g: 1, fat_g: 7, fiber_g: 1, sodium_mg: 600 }),
  f("Lor Mai Kai (glutinous rice chicken)", "1 bowl", ["high-glycemic"], { kcal: 324, protein_g: 12, carbs_g: 45, sugar_g: 3, fat_g: 11, fiber_g: 1, sodium_mg: 700 }),
  f("Chee Cheong Fun (2 rolls, sauce)", "2 rolls", [], { kcal: 258, protein_g: 6, carbs_g: 42, sugar_g: 6, fat_g: 7, fiber_g: 1, sodium_mg: 800 }),
  f("Soon Kway (steamed, 1)", "1 piece", [], { kcal: 89, protein_g: 3, carbs_g: 15, sugar_g: 2, fat_g: 2, fiber_g: 1, sodium_mg: 300 }),
  f("Taukwa Pok (with vegetables)", "1 portion", [], { kcal: 179, protein_g: 10, carbs_g: 12, sugar_g: 3, fat_g: 10, fiber_g: 2, sodium_mg: 600 }),
  f("BBQ Chicken Wings (2 pcs)", "2 wings", ["high-protein"], { kcal: 196, protein_g: 18, carbs_g: 2, sugar_g: 1, fat_g: 13, fiber_g: 0, sodium_mg: 500 }),
  f("Otah (2 pcs)", "2 pieces", [], { kcal: 130, protein_g: 8, carbs_g: 4, sugar_g: 2, fat_g: 9, fiber_g: 1, sodium_mg: 500 }),
  f("Masala Thosai", "1 piece", ["high-glycemic"], { kcal: 362, protein_g: 10, carbs_g: 55, sugar_g: 4, fat_g: 11, fiber_g: 4, sodium_mg: 800 }),
  f("Chendol", "1 bowl", ["high-sugar", "high-fat"], { kcal: 420, protein_g: 4, carbs_g: 62, sugar_g: 48, fat_g: 16, fiber_g: 2, sodium_mg: 120 }),
  f("Ice Kacang", "1 bowl", ["high-sugar"], { kcal: 257, protein_g: 3, carbs_g: 55, sugar_g: 45, fat_g: 3, fiber_g: 2, sodium_mg: 80 }),
  f("Tau Huay (beancurd, sweet)", "1 bowl", ["high-sugar"], { kcal: 200, protein_g: 8, carbs_g: 32, sugar_g: 26, fat_g: 4, fiber_g: 1, sodium_mg: 40 }),
  f("Tau Suan (with you tiao)", "1 bowl", ["high-sugar"], { kcal: 293, protein_g: 6, carbs_g: 55, sugar_g: 30, fat_g: 5, fiber_g: 3, sodium_mg: 200 }),
  f("Cheng Tng", "1 bowl", ["high-sugar"], { kcal: 188, protein_g: 2, carbs_g: 44, sugar_g: 35, fat_g: 1, fiber_g: 2, sodium_mg: 60 }),
  f("Bubur Cha Cha", "1 bowl", ["high-sugar", "high-fat"], { kcal: 390, protein_g: 4, carbs_g: 60, sugar_g: 35, fat_g: 15, fiber_g: 4, sodium_mg: 100 }),
  f("Pulut Hitam (black glutinous)", "1 bowl", ["high-sugar"], { kcal: 290, protein_g: 5, carbs_g: 52, sugar_g: 28, fat_g: 8, fiber_g: 3, sodium_mg: 60 }),
  f("Peanut Soup (with tang yuan)", "1 bowl", ["high-sugar"], { kcal: 255, protein_g: 8, carbs_g: 40, sugar_g: 25, fat_g: 8, fiber_g: 3, sodium_mg: 80 }),
  f("Goreng Pisang (banana fritter)", "1 piece", ["high-fat"], { kcal: 197, protein_g: 2, carbs_g: 30, sugar_g: 12, fat_g: 8, fiber_g: 2, sodium_mg: 100 }),
  f("Waffle with Kaya", "1 waffle", ["high-sugar"], { kcal: 400, protein_g: 8, carbs_g: 55, sugar_g: 20, fat_g: 16, fiber_g: 2, sodium_mg: 400 }),
  f("Nonya Rice Dumpling (Bak Chang)", "1 dumpling", ["high-glycemic"], { kcal: 352, protein_g: 12, carbs_g: 50, sugar_g: 6, fat_g: 11, fiber_g: 2, sodium_mg: 700 }),
  f("Ya Kun Kaya Toast Set", "2 toast + 2 soft eggs + kopi", ["high-sugar", "high-fat"], { kcal: 480, protein_g: 15, carbs_g: 45, sugar_g: 18, fat_g: 27, fiber_g: 2, sodium_mg: 650 }, "Ya Kun"),
  f("Toast Box Kaya Butter Toast (2)", "2 toast", ["high-sugar", "high-fat"], { kcal: 320, protein_g: 7, carbs_g: 40, sugar_g: 14, fat_g: 15, fiber_g: 2, sodium_mg: 450 }, "Toast Box"),
  f("Old Chang Kee Curry'O (1 puff)", "1 puff", ["high-fat"], { kcal: 290, protein_g: 6, carbs_g: 25, sugar_g: 3, fat_g: 18, fiber_g: 2, sodium_mg: 450 }, "Old Chang Kee"),
  f("Xiao Long Bao (Din Tai Fung, 5 pcs)", "5 pieces", [], { kcal: 305, protein_g: 15, carbs_g: 30, sugar_g: 2, fat_g: 12, fiber_g: 1, sodium_mg: 700 }, "Din Tai Fung"),
  f("Mr Bean Soya Milk (sweetened)", "1 cup (~250ml)", ["high-sugar"], { kcal: 130, protein_g: 6, carbs_g: 20, sugar_g: 16, fat_g: 3, fiber_g: 1, sodium_mg: 50 }, "Mr Bean"),
  f("Mr Bean Pancake (red bean)", "1 pancake", [], { kcal: 140, protein_g: 4, carbs_g: 22, sugar_g: 10, fat_g: 4, fiber_g: 1, sodium_mg: 120 }, "Mr Bean"),
  f("4Fingers Crispy Chicken (3 wings)", "3 wings", ["high-fat", "high-protein"], { kcal: 350, protein_g: 24, carbs_g: 18, sugar_g: 6, fat_g: 20, fiber_g: 1, sodium_mg: 900 }, "4Fingers"),
  f("A&W Root Beer Float", "1 regular", ["high-sugar"], { kcal: 220, protein_g: 3, carbs_g: 45, sugar_g: 42, fat_g: 4, fiber_g: 0, sodium_mg: 60 }, "A&W"),
  f("Thosai (plain)", "1 piece", ["high-glycemic"], { kcal: 100, protein_g: 3, carbs_g: 18, sugar_g: 1, fat_g: 2, fiber_g: 1, sodium_mg: 300 }),
  f("Idli (2 pcs)", "2 pieces", [], { kcal: 120, protein_g: 4, carbs_g: 24, sugar_g: 1, fat_g: 1, fiber_g: 1, sodium_mg: 250 }),
  f("Chapati (2, plain)", "2 pieces", [], { kcal: 240, protein_g: 8, carbs_g: 40, sugar_g: 2, fat_g: 6, fiber_g: 4, sodium_mg: 400 }),
  f("Appam (2 pcs)", "2 pieces", [], { kcal: 220, protein_g: 4, carbs_g: 40, sugar_g: 6, fat_g: 5, fiber_g: 1, sodium_mg: 200 }),
  f("Vadai (2 pcs)", "2 pieces", ["high-fat"], { kcal: 200, protein_g: 6, carbs_g: 20, sugar_g: 1, fat_g: 10, fiber_g: 3, sodium_mg: 400 }),
  f("Putu Mayam (with sugar & coconut)", "1 serving", ["high-sugar"], { kcal: 250, protein_g: 4, carbs_g: 45, sugar_g: 15, fat_g: 6, fiber_g: 2, sodium_mg: 100 }),
  f("Ayam Penyet (with rice)", "1 plate", ["high-fat", "high-glycemic"], { kcal: 700, protein_g: 35, carbs_g: 75, sugar_g: 5, fat_g: 28, fiber_g: 4, sodium_mg: 1400 }),
  f("Nasi Padang (rice + 3 dishes)", "1 plate", ["high-fat", "high-glycemic"], { kcal: 750, protein_g: 28, carbs_g: 85, sugar_g: 8, fat_g: 32, fiber_g: 5, sodium_mg: 1500 }),
  f("Tauhu Goreng (with peanut sauce)", "1 plate", ["high-fat"], { kcal: 450, protein_g: 16, carbs_g: 30, sugar_g: 10, fat_g: 28, fiber_g: 5, sodium_mg: 800 }),
  f("Sup Tulang (mutton bone)", "1 bowl", ["high-fat", "high-sodium"], { kcal: 450, protein_g: 30, carbs_g: 20, sugar_g: 6, fat_g: 26, fiber_g: 2, sodium_mg: 1300 }),
  f("Sup Kambing (mutton soup)", "1 bowl", ["high-sodium"], { kcal: 300, protein_g: 28, carbs_g: 8, sugar_g: 3, fat_g: 17, fiber_g: 1, sodium_mg: 1400 }),
  f("Beef Rendang (with rice)", "1 plate", ["high-fat", "high-glycemic"], { kcal: 680, protein_g: 32, carbs_g: 72, sugar_g: 6, fat_g: 28, fiber_g: 4, sodium_mg: 1200 }),
  f("Ayam Buah Keluak (Peranakan)", "1 serving", ["high-fat"], { kcal: 480, protein_g: 26, carbs_g: 15, sugar_g: 4, fat_g: 34, fiber_g: 2, sodium_mg: 900 }),
  f("Nasi Briyani (Mutton)", "1 plate", ["high-fat", "high-glycemic"], { kcal: 900, protein_g: 34, carbs_g: 95, sugar_g: 6, fat_g: 40, fiber_g: 4, sodium_mg: 1600 }),
  f("Roti Prata (plain, 1)", "1 piece", ["high-glycemic"], { kcal: 120, protein_g: 3, carbs_g: 18, sugar_g: 2, fat_g: 4, fiber_g: 1, sodium_mg: 200 }),
  f("Kolo Mee", "1 bowl", ["high-glycemic"], { kcal: 480, protein_g: 20, carbs_g: 60, sugar_g: 5, fat_g: 18, fiber_g: 3, sodium_mg: 1300 }),
  f("Mala Xiang Guo (dry)", "1 bowl", ["high-fat", "high-sodium"], { kcal: 650, protein_g: 25, carbs_g: 45, sugar_g: 6, fat_g: 40, fiber_g: 5, sodium_mg: 2000 }),
  f("Herbal Chicken Soup", "1 bowl", ["high-protein"], { kcal: 250, protein_g: 28, carbs_g: 6, sugar_g: 3, fat_g: 13, fiber_g: 1, sodium_mg: 1100 }),
  f("Salted Vegetable Duck Soup (Kiam Chai Ark)", "1 bowl", ["high-sodium"], { kcal: 220, protein_g: 20, carbs_g: 10, sugar_g: 3, fat_g: 12, fiber_g: 2, sodium_mg: 1500 }),
  f("Prawn Mee (dry)", "1 bowl", ["high-glycemic"], { kcal: 461, protein_g: 22, carbs_g: 60, sugar_g: 4, fat_g: 14, fiber_g: 3, sodium_mg: 1500 }),
  f("Yong Tau Foo (dry, with sauce)", "1 plate", ["balanced"], { kcal: 420, protein_g: 24, carbs_g: 48, sugar_g: 6, fat_g: 14, fiber_g: 5, sodium_mg: 1400 }),
  f("Ban Mian (dry)", "1 bowl", ["high-glycemic"], { kcal: 500, protein_g: 24, carbs_g: 62, sugar_g: 4, fat_g: 17, fiber_g: 3, sodium_mg: 1500 }),
  f("Fried Wanton (8 pcs)", "8 pieces", ["high-fat"], { kcal: 320, protein_g: 12, carbs_g: 25, sugar_g: 3, fat_g: 19, fiber_g: 1, sodium_mg: 700 }),
  f("Sliced Fish Soup (with milk, no rice)", "1 bowl", ["high-fat"], { kcal: 350, protein_g: 28, carbs_g: 12, sugar_g: 3, fat_g: 20, fiber_g: 2, sodium_mg: 1300 }),
  f("Kopi C", "1 cup", [], { kcal: 90, protein_g: 3, carbs_g: 12, sugar_g: 10, fat_g: 3, fiber_g: 0, sodium_mg: 40 }),
  f("Kopi C Kosong", "1 cup", [], { kcal: 40, protein_g: 2, carbs_g: 3, sugar_g: 2, fat_g: 2, fiber_g: 0, sodium_mg: 30 }),
  f("Teh C", "1 cup", [], { kcal: 90, protein_g: 3, carbs_g: 12, sugar_g: 10, fat_g: 3, fiber_g: 0, sodium_mg: 40 }),
  f("Teh (with condensed milk)", "1 cup", ["high-sugar"], { kcal: 120, protein_g: 3, carbs_g: 20, sugar_g: 18, fat_g: 3, fiber_g: 0, sodium_mg: 40 }),
  f("Milo (hot, kopitiam)", "1 cup", ["high-sugar"], { kcal: 180, protein_g: 6, carbs_g: 30, sugar_g: 25, fat_g: 4, fiber_g: 1, sodium_mg: 100 }),
  f("Iced Lemon Tea (kopitiam)", "1 cup", ["high-sugar"], { kcal: 120, protein_g: 0, carbs_g: 30, sugar_g: 28, fat_g: 0, fiber_g: 0, sodium_mg: 20 }),
  f("Kopi Peng (iced)", "1 cup", ["high-sugar"], { kcal: 130, protein_g: 3, carbs_g: 22, sugar_g: 18, fat_g: 3, fiber_g: 0, sodium_mg: 40 }),
  f("Yuan Yang", "1 cup", ["high-sugar"], { kcal: 120, protein_g: 3, carbs_g: 20, sugar_g: 17, fat_g: 3, fiber_g: 0, sodium_mg: 40 }),
  f("Fresh Coconut (water + flesh)", "1 coconut", [], { kcal: 140, protein_g: 2, carbs_g: 20, sugar_g: 12, fat_g: 6, fiber_g: 3, sodium_mg: 40 }),
  f("McSpicy (McDonald’s)", "1 burger", ["high-fat", "high-sodium"], { kcal: 540, protein_g: 28, carbs_g: 45, sugar_g: 6, fat_g: 29, fiber_g: 3, sodium_mg: 1200 }, "McDonald’s"),
  f("Filet-O-Fish (McDonald’s)", "1 burger", [], { kcal: 333, protein_g: 15, carbs_g: 38, sugar_g: 5, fat_g: 14, fiber_g: 2, sodium_mg: 620 }, "McDonald’s"),
  f("Fries, medium (McDonald’s)", "1 medium", ["high-fat"], { kcal: 330, protein_g: 4, carbs_g: 42, sugar_g: 0, fat_g: 16, fiber_g: 4, sodium_mg: 260 }, "McDonald’s"),
  f("Chicken McNuggets (6 pc)", "6 pieces", [], { kcal: 250, protein_g: 14, carbs_g: 15, sugar_g: 0, fat_g: 15, fiber_g: 1, sodium_mg: 500 }, "McDonald’s"),
  f("KFC Fried Chicken (2 pc)", "2 pieces", ["high-fat", "high-protein"], { kcal: 500, protein_g: 40, carbs_g: 12, sugar_g: 0, fat_g: 32, fiber_g: 1, sodium_mg: 1200 }, "KFC"),
  f("KFC Zinger Burger", "1 burger", ["high-fat"], { kcal: 450, protein_g: 24, carbs_g: 40, sugar_g: 6, fat_g: 22, fiber_g: 2, sodium_mg: 1000 }, "KFC"),
  f("Subway 6\" Chicken Teriyaki", "6-inch", ["balanced"], { kcal: 370, protein_g: 24, carbs_g: 55, sugar_g: 12, fat_g: 6, fiber_g: 5, sodium_mg: 900 }, "Subway"),
  f("Song Fa Bak Kut Teh (with rice)", "1 set", ["high-protein", "high-sodium"], { kcal: 450, protein_g: 32, carbs_g: 50, sugar_g: 2, fat_g: 12, fiber_g: 1, sodium_mg: 1800 }, "Song Fa"),
  f("BreadTalk Floss Bun", "1 bun", ["high-sugar"], { kcal: 230, protein_g: 6, carbs_g: 30, sugar_g: 8, fat_g: 9, fiber_g: 1, sodium_mg: 300 }, "BreadTalk"),
  f("Polar Curry Puff", "1 puff", ["high-fat"], { kcal: 280, protein_g: 6, carbs_g: 25, sugar_g: 3, fat_g: 17, fiber_g: 2, sodium_mg: 400 }, "Polar"),
  f("Beard Papa Cream Puff", "1 puff", ["high-sugar"], { kcal: 230, protein_g: 4, carbs_g: 22, sugar_g: 12, fat_g: 14, fiber_g: 0, sodium_mg: 120 }, "Beard Papa"),
  f("Jollibean Soya + You Tiao", "1 set", [], { kcal: 250, protein_g: 8, carbs_g: 38, sugar_g: 12, fat_g: 8, fiber_g: 1, sodium_mg: 200 }, "Jollibean"),
  f("Killiney Kaya Toast Set", "2 toast + 2 eggs + kopi", ["high-sugar", "high-fat"], { kcal: 470, protein_g: 15, carbs_g: 45, sugar_g: 18, fat_g: 26, fiber_g: 2, sodium_mg: 650 }, "Killiney"),
  f("LiHo Brown Sugar Bubble Milk", "1 cup", ["high-sugar"], { kcal: 350, protein_g: 3, carbs_g: 65, sugar_g: 55, fat_g: 8, fiber_g: 0, sodium_mg: 60 }, "LiHo"),
  f("Din Tai Fung Fried Rice", "1 plate", ["high-glycemic"], { kcal: 550, protein_g: 16, carbs_g: 75, sugar_g: 4, fat_g: 20, fiber_g: 2, sodium_mg: 1200 }, "Din Tai Fung"),
];

module.exports = SEED;
